proxy:
  port: 8080
  container-wait-time: 40000
  template-path: /templates/2col
  authentication: none
  admin-groups: admin
  hide-navbar: true
  users:
  - name: admin
    password: admin
    groups: admin, collaborators
  container-backend: docker
  docker:
    internal-networking: true
  specs:
  - id: milkyway
    display-name: MilkyWay Proteomics
    description: An interface to the Galaxy MilkyWay Workflow System
    container-image: wbarshop/milkyway_shiny:dev
    container-network: milkyway-stack-ci_milkynet
spring:
  servlet:
    multipart:
      max-file-size: 90000MB
      max-request-size: 90000MB

logging:
  file: shinyproxy.log
